"""
causelink/patterns/library.py

Hypothesis Pattern Library — Phase E.

Design:
  - HypothesisPattern describes a causal template rooted in the ontology.
  - Each pattern declares REQUIRED node labels, relationship types, and
    evidence types — all must be satisfied before the pattern fires.
  - HypothesisPatternLibrary.match() evaluates the CanonGraph + evidence
    against every registered pattern and returns PatternMatchResult list.
  - The HypothesisGeneratorAgent calls this library; LLM only fills
    description text (entity names/IDs), never the structural shape.

Pattern library is EXTENDABLE: call HypothesisPatternLibrary.register()
to add custom patterns without modifying this file.

Non-negotiable constraint:
  No hypothesis may be created without a matching pattern that has its
  required_node_labels, required_rel_types, and required_evidence_types
  all satisfied.  This is enforced by PatternMatchResult.satisfied.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, FrozenSet, List, Optional, Set

from causelink.evidence.contracts import EvidenceObject, EvidenceType
from causelink.ontology.models import CanonGraph

logger = logging.getLogger(__name__)


# ─── HypothesisPattern ────────────────────────────────────────────────────────


@dataclass(frozen=True)
class HypothesisPattern:
    """
    A causal template grounded in the ontology schema.

    Fields:
        pattern_id              — stable ID used as Hypothesis.pattern_id
        name                    — human-readable name
        description_template    — template with {placeholders} for LLM fill-in
        required_node_labels    — ALL must be present in CanonGraph.nodes
        required_rel_types      — ALL must appear in at least one CanonGraph.edges
        required_evidence_types — ALL must match at least one EvidenceObject.type
        anchor_types            — pattern applicable when anchor is one of these
        confidence_prior        — base confidence assigned to generated hypotheses
        chain                   — which backtracking chain this pattern belongs to
    """

    pattern_id: str
    name: str
    description_template: str
    required_node_labels: FrozenSet[str]
    required_rel_types: FrozenSet[str]
    required_evidence_types: FrozenSet[EvidenceType]
    anchor_types: FrozenSet[str]
    confidence_prior: float = 0.40
    chain: str = "general"

    def anchor_matches(self, anchor_type: str) -> bool:
        return not self.anchor_types or anchor_type in self.anchor_types


# ─── PatternMatchResult ───────────────────────────────────────────────────────


@dataclass
class PatternMatchResult:
    """
    Result of matching a HypothesisPattern against the current InvestigationState.

    satisfied=True  → all requirements met; hypothesis may be generated.
    satisfied=False → requirements unmet; hypothesis MUST NOT be generated.
    """

    pattern: HypothesisPattern
    satisfied: bool
    matched_node_ids: List[str] = field(default_factory=list)
    matched_rel_types: List[str] = field(default_factory=list)
    matched_evidence_ids: List[str] = field(default_factory=list)
    unmet_node_labels: List[str] = field(default_factory=list)
    unmet_rel_types: List[str] = field(default_factory=list)
    unmet_evidence_types: List[str] = field(default_factory=list)
    # Additional context filled in by the matcher for template substitution
    template_vars: Dict[str, Any] = field(default_factory=dict)


# ─── Built-in patterns ────────────────────────────────────────────────────────


BUILT_IN_PATTERNS: List[HypothesisPattern] = [

    # ── Compliance chain patterns ─────────────────────────────────────────

    HypothesisPattern(
        pattern_id="CLK-P001",
        name="Incident triggered by compliance violation",
        description_template=(
            "Incident {anchor_value} was triggered by Violation {violation_value} "
            "which was generated by rule enforcement failure on Pipeline {pipeline_value}."
        ),
        required_node_labels=frozenset({"Incident", "Violation"}),
        required_rel_types=frozenset({"GENERATES"}),
        required_evidence_types=frozenset({EvidenceType.AUDIT_EVENT}),
        anchor_types=frozenset({"Incident"}),
        confidence_prior=0.60,
        chain="compliance",
    ),

    HypothesisPattern(
        pattern_id="CLK-P002",
        name="Rule not implemented — control gap",
        description_template=(
            "Regulation {regulation_value} mandates Rule {rule_value} which has "
            "no Transformation implementing it in Pipeline {pipeline_value}. "
            "This control gap allowed Incident {anchor_value} to occur."
        ),
        required_node_labels=frozenset({"Regulation", "Rule", "Pipeline"}),
        required_rel_types=frozenset({"MANDATES", "HAS_TRANSFORMATION"}),
        required_evidence_types=frozenset({EvidenceType.AUDIT_EVENT}),
        anchor_types=frozenset({"Incident", "Violation"}),
        confidence_prior=0.55,
        chain="compliance",
    ),

    HypothesisPattern(
        pattern_id="CLK-P003",
        name="Pipeline execution failure — job root cause",
        description_template=(
            "System {system_value} running Job {job_value} produced a failure "
            "that escalated to Incident {anchor_value}. "
            "Job execution logs confirm abnormal termination."
        ),
        required_node_labels=frozenset({"System", "Job"}),
        required_rel_types=frozenset({"RUNS_JOB"}),
        required_evidence_types=frozenset({EvidenceType.LOG}),
        anchor_types=frozenset({"Incident"}),
        confidence_prior=0.65,
        chain="compliance",
    ),

    # ── Data lineage chain patterns ───────────────────────────────────────

    HypothesisPattern(
        pattern_id="CLK-P004",
        name="Upstream column drift cascaded downstream",
        description_template=(
            "Column {upstream_column_value} in Table {table_value} was changed, "
            "and Column {downstream_column_value} is DERIVED_FROM it. "
            "The schema drift propagated to Pipeline {anchor_value}."
        ),
        required_node_labels=frozenset({"Column", "Table"}),
        required_rel_types=frozenset({"DERIVED_FROM", "HAS_COLUMN"}),
        required_evidence_types=frozenset({EvidenceType.LINEAGE_TRACE}),
        anchor_types=frozenset({"Pipeline", "Job"}),
        confidence_prior=0.58,
        chain="lineage",
    ),

    HypothesisPattern(
        pattern_id="CLK-P005",
        name="Script reads from degraded table",
        description_template=(
            "Script {script_value} used by Pipeline {anchor_value} reads "
            "Table {table_value} which shows data quality degradation in "
            "evidence period {time_start} – {time_end}."
        ),
        required_node_labels=frozenset({"Script", "Table"}),
        required_rel_types=frozenset({"READS", "USES_SCRIPT"}),
        required_evidence_types=frozenset({EvidenceType.LOG, EvidenceType.METRIC}),
        anchor_types=frozenset({"Pipeline", "Job"}),
        confidence_prior=0.50,
        chain="lineage",
    ),

    # ── Change provenance patterns ────────────────────────────────────────

    HypothesisPattern(
        pattern_id="CLK-P006",
        name="Recent CodeEvent changed a script used by the pipeline",
        description_template=(
            "Script {script_value} used by Pipeline {anchor_value} was modified "
            "by CodeEvent {code_event_value} shortly before the incident. "
            "The change introduced the failure."
        ),
        required_node_labels=frozenset({"Script", "CodeEvent"}),
        required_rel_types=frozenset({"CHANGED_BY", "USES_SCRIPT"}),
        required_evidence_types=frozenset({EvidenceType.CHANGE_EVENT}),
        anchor_types=frozenset({"Incident", "Pipeline", "Job"}),
        confidence_prior=0.62,
        chain="change_provenance",
    ),

    # ── Log scope patterns ────────────────────────────────────────────────

    HypothesisPattern(
        pattern_id="CLK-P007",
        name="LogSource contains error evidence for the job",
        description_template=(
            "Job {anchor_value} logs in LogSource {log_source_value} contain "
            "error-level entries that correlate with the reported Incident."
        ),
        required_node_labels=frozenset({"LogSource"}),
        required_rel_types=frozenset({"LOGGED_IN"}),
        required_evidence_types=frozenset({EvidenceType.LOG}),
        anchor_types=frozenset({"System", "Job", "Pipeline"}),
        confidence_prior=0.45,
        chain="log_scope",
    ),

    # ── Operational / combined patterns ───────────────────────────────────

    HypothesisPattern(
        pattern_id="CLK-P008",
        name="Violation assigned to owner with no remediation",
        description_template=(
            "Violation {violation_value} was assigned to Owner {owner_value} "
            "but has no associated Remediation node. "
            "Absence of remediation allowed the issue to escalate to Incident {anchor_value}."
        ),
        required_node_labels=frozenset({"Violation", "Owner"}),
        required_rel_types=frozenset({"ASSIGNED_TO"}),
        required_evidence_types=frozenset({EvidenceType.AUDIT_EVENT}),
        anchor_types=frozenset({"Incident", "Violation"}),
        confidence_prior=0.50,
        chain="compliance",
    ),
]


# ─── HypothesisPatternLibrary ─────────────────────────────────────────────────


class HypothesisPatternLibrary:
    """
    Registry of hypothesis patterns.

    Usage::

        library = HypothesisPatternLibrary()
        results = library.match(graph, evidence_objects, anchor_type="Incident")
        for r in results:
            if r.satisfied:
                # generate hypothesis from r.pattern
    """

    def __init__(self, extra_patterns: Optional[List[HypothesisPattern]] = None) -> None:
        self._patterns: List[HypothesisPattern] = list(BUILT_IN_PATTERNS)
        if extra_patterns:
            self._patterns.extend(extra_patterns)

    def register(self, pattern: HypothesisPattern) -> None:
        """Add a custom pattern to the library at runtime."""
        if any(p.pattern_id == pattern.pattern_id for p in self._patterns):
            raise ValueError(
                f"Pattern '{pattern.pattern_id}' already registered. "
                "Use a unique pattern_id."
            )
        self._patterns.append(pattern)

    def get(self, pattern_id: str) -> Optional[HypothesisPattern]:
        for p in self._patterns:
            if p.pattern_id == pattern_id:
                return p
        return None

    def all_patterns(self) -> List[HypothesisPattern]:
        return list(self._patterns)

    def match(
        self,
        graph: CanonGraph,
        evidence_objects: List[EvidenceObject],
        anchor_type: str,
    ) -> List[PatternMatchResult]:
        """
        Evaluate every registered pattern against *graph* and *evidence_objects*.

        Returns one PatternMatchResult per pattern regardless of satisfaction.
        Callers MUST check result.satisfied before generating a hypothesis.
        """
        results: List[PatternMatchResult] = []

        # Pre-build lookup sets for O(1) checks
        present_labels: Set[str] = {
            lbl for node in graph.nodes for lbl in node.labels
        }
        present_rel_types: Set[str] = {edge.type for edge in graph.edges}
        present_ev_types: Set[EvidenceType] = {ev.type for ev in evidence_objects}
        # Map label → node ids
        label_to_ids: Dict[str, List[str]] = {}
        for node in graph.nodes:
            for lbl in node.labels:
                label_to_ids.setdefault(lbl, []).append(node.neo4j_id)

        for pattern in self._patterns:
            if not pattern.anchor_matches(anchor_type):
                results.append(PatternMatchResult(
                    pattern=pattern,
                    satisfied=False,
                    unmet_node_labels=["anchor_type_mismatch"],
                ))
                continue

            unmet_nodes = [
                lbl for lbl in pattern.required_node_labels
                if lbl not in present_labels
            ]
            unmet_rels = [
                rt for rt in pattern.required_rel_types
                if rt not in present_rel_types
            ]
            unmet_ev = [
                et.value for et in pattern.required_evidence_types
                if et not in present_ev_types
            ]

            satisfied = not unmet_nodes and not unmet_rels and not unmet_ev

            # Collect matched node IDs for the template
            matched_node_ids: List[str] = []
            for lbl in pattern.required_node_labels:
                matched_node_ids.extend(label_to_ids.get(lbl, []))

            matched_rel_types = [
                rt for rt in pattern.required_rel_types
                if rt in present_rel_types
            ]
            matched_evidence_ids = [
                ev.evidence_id for ev in evidence_objects
                if ev.type in pattern.required_evidence_types
            ]

            # Build template vars from matched nodes
            template_vars: Dict[str, Any] = {
                "anchor_value": graph.anchor_primary_value,
            }
            for lbl in pattern.required_node_labels:
                ids = label_to_ids.get(lbl, [])
                if ids:
                    node = graph.get_node(ids[0])
                    if node:
                        key = f"{lbl.lower()}_value"
                        template_vars[key] = node.primary_value or ids[0]

            if satisfied:
                logger.debug("Pattern %s matched for anchor=%s", pattern.pattern_id, anchor_type)
            else:
                logger.debug(
                    "Pattern %s not satisfied: unmet_nodes=%s unmet_rels=%s unmet_ev=%s",
                    pattern.pattern_id, unmet_nodes, unmet_rels, unmet_ev
                )

            results.append(PatternMatchResult(
                pattern=pattern,
                satisfied=satisfied,
                matched_node_ids=matched_node_ids,
                matched_rel_types=matched_rel_types,
                matched_evidence_ids=matched_evidence_ids,
                unmet_node_labels=unmet_nodes,
                unmet_rel_types=unmet_rels,
                unmet_evidence_types=unmet_ev,
                template_vars=template_vars,
            ))

        satisfied_count = sum(1 for r in results if r.satisfied)
        logger.info(
            "Pattern matching: %d/%d patterns satisfied for anchor_type=%s",
            satisfied_count, len(results), anchor_type,
        )
        return results
